### ISSUE TITLE
Station-fetch doesn't handle missing weather values

### ISSUE THREAD

**Issue by wgpage** [firelab/windninja#278] opened 2017-11-15 18:49 UTC
When match points is "true" the solver hangs up on the hour with a missing value. When match points is "false" the solver returns "-2147483648% complete" for endless loops. See example config file.

Would also be nice to include an option that sets a time limit for solving, so it doesn't sit on a problem forever.
@nwagenbrenner @tfinney9 

[wind.txt](https://github.com/firelab/windninja/files/1475940/wind.txt)

**Comment by nwagenbrenner** [comment] 2017-11-17 13:50
@tfinney9 is this something you can look into? Did you have a scheme for handling missing values in a time series? There must be some problem with our interpolation method. Maybe you can run the example cfg that Wesley attached and see what's going on?

**Comment by tfinney9** [comment] 2017-11-18 23:48
Interesting, I've done some messing around with cfg and I catch errors both times, indicating bad data.

tanner@suez:~/src/wind/build-clion/src/cli$ ./WindNinja_cli wind.cfg 
Downloading elevation file...

/home/tanner/src/wind/build-clion/src/cli/tif/Buck_stations_1.csv
failed cloud check on 96
-1.59949e-262
failed cloud check on 96
-1.59949e-262
Exception caught: Error in weather station parameters.

This might be due to some sort of error in the interpolation, I'll keep looking.

**Comment by tfinney9** [comment] 2017-11-19 00:46
I think I found where the issue is. The sanity checks for station-fetch generally checks for values less than 0.0 but nans are not considered less than zero. I've rectified this with an additional check with isnan(). I'll commit this soon.

**Comment by wgpage** [comment] 2018-01-18 17:37
Seems I'm getting the same problem with another file. I believe I have correctly rebuilt windninja with the updates to station-fetch. See example file.
[wind.txt](https://github.com/firelab/windninja/files/1643865/wind.txt)

**Comment by tfinney9** [comment] 2018-01-18 17:46
I'll run that and see what I can find.

**Comment by tfinney9** [comment] 2018-06-22 20:11
Fixed with 
22e8098452c3e8fe689d988f6ef0ce28c373a48e
which reworked the station fetching part so that empty stations are robustly handled if they are missing a sensor

and
96132f3362ba0c48a0eaf2be8448d113ff755ea7
which reworked the temporal interpolation

**Closed by tfinney9** 2018-06-22 20:11 UTC
Labels: bug, component:point, priority:high, severity:high
