### ISSUE TITLE
NEW ZEALAND SUMMER AND SPRING BUG

### ISSUE THREAD

**Issue by JFL81** [firelab/windninja#386] opened 2020-09-17 00:28 UTC
Hello,

I've been trying to do wind simulations in New Zealand using WindNinja but I can't input station data with any summer or spring months (from October to march) so I tried with other longitudes and this same latitude and had the same problem in Tasmania, Chile and Argentina.
I'll be grateful if you address this bug

**Comment by ksshannon** [comment] 2020-09-17 02:23
Hi, can you provide us with some details so we can reproduce the problem:
- version of WindNinja
- a DEM file
- a station file

Is there any error or message?  Thanks.

**Comment by JFL81** [comment] 2020-09-17 07:47
Hello Kyle,

WindNinja version: 3.5.3
DEM: Blenheim3WS tif attached
Station file: MTG_2_STATION_cloud0 csv

No error message the program just shuts down
________________________________

**Comment by ksshannon** [comment] 2020-09-17 15:46
There are no attachments, you may have to use the issue tracker to attach them.

**Comment by JFL81** [comment] 2020-09-17 20:49
Sorry Kyle,

I answered through the email. I tried right now from the site but can only upload the zip file. Hope you can open it, tell me otherwise.

Regards
[Re__[firelab_windninja]_NEW_ZEALAND_SUMMER_AND_SPRING_BUG_(#386).zip](https://github.com/firelab/windninja/files/5241742/Re__.firelab_windninja._NEW_ZEALAND_SUMMER_AND_SPRING_BUG_.386.zip)

**Comment by ksshannon** [comment] 2020-09-17 22:28
This is a little foreign to me, I'm going to loop in some other folks.

/cc @nwagenbrenner , @tfinney9 

Boost is throwing:

```
s_dst flag does not match resulting dst for time label given: flag given: dst=false, dst calculated: dst=true
```
[here](https://github.com/firelab/windninja/blob/f5cb1b00f3e710ef98577468fab669088b78f2b5/src/ninja/pointInitialization.cpp#L2563).  It looks like we may be comparing utc and local times, but I don't know my way around in this to comment more.

**Comment by ksshannon** [comment] 2020-09-17 22:57
I can confirm that changing the dst flag on [this](https://github.com/firelab/windninja/blob/f5cb1b00f3e710ef98577468fab669088b78f2b5/src/ninja/pointInitialization.cpp#L2563) line and [this](https://github.com/firelab/windninja/blob/f5cb1b00f3e710ef98577468fab669088b78f2b5/src/ninja/pointInitialization.cpp#L2576) line at least lets the model run.  Why we are checking for DST manually here, I don't know.  We'll have to wait from feedback from the other developers before we get more information.

**Comment by JFL81** [comment] 2020-09-24 02:56
Hello Kyle,

Was there any development on this bug?

Regards,
JF

On Sep 18, 2020 10:58, Kyle Shannon <notifications@github.com> wrote:

I can confirm that changing the dst flag on this<https://github.com/firelab/windninja/blob/f5cb1b00f3e710ef98577468fab669088b78f2b5/src/ninja/pointInitialization.cpp#L2563> line and this<https://github.com/firelab/windninja/blob/f5cb1b00f3e710ef98577468fab669088b78f2b5/src/ninja/pointInitialization.cpp#L2576> line at least lets the model run. Why we are checking for DST manually here, I don't know. We'll have to wait from feedback from the other developers before we get more information.

**Comment by ksshannon** [comment] 2020-09-24 03:29
Sorry, no.  We'll have to wait for @nwagenbrenner to make the next step, and I think she is on a fire.

**Comment by tfinney9** [comment] 2020-10-07 04:20
I took a look at this and I think I have a solution, though I am not sure how robust it is. 

Long story short, I think when I wrote this code, I wasn't fully aware of all the different constructor options for the `boost::local_time::local_date_time` object. 

Looking here: https://www.boost.org/doc/libs/1_49_0/doc/html/date_time/local_time.html

One construction option (second option from the table under header Construction) has a bool to specify whether or not the time zone is currently in DST, not really sure why. I am also not sure why I chose to use this one, as then it required us to manually check the start and stop times to figure out whether we were in DST. 

This actually works fine if you are using a time zone with DST in the northern hemisphere, as the DST happens in the same calendar year, and a simple comparison can be made. 

This is flipped for the southern hemisphere, meaning the simple check that I had in there doesn't work, hence the bug.  https://en.wikipedia.org/wiki/Time_in_New_Zealand

The first construction option I think fixes this, because we just let boost figure itself out, as it can do the DST calculations internally (I think). 

I propose replacing that mess of comparison code (lines ~2550-2573) https://github.com/firelab/windninja/blob/2e12ce0ae2801085cd7a6a12d6e58df677d7f3ea/src/ninja/pointInitialization.cpp#L2550 - https://github.com/firelab/windninja/blob/2e12ce0ae2801085cd7a6a12d6e58df677d7f3ea/src/ninja/pointInitialization.cpp#L2573 with this:

```
blt::local_date_time startLocal = blt::local_date_time(utcStart,timeZonePtr);
blt::local_date_time endLocal= blt::local_date_time(utcEnd,timeZonePtr);

CPLDebug("STATION_FETCH","Start Time is DST?: %i", startLocal.is_dst());
CPLDebug("STATION_FETCH","End Time is DST?: %i", endLocal.is_dst());
```
I tested this both with the NZ time zone and America/Denver, and both seemed to work, though I haven't fully tested this to ensure that it works for all cases. 

Do you want me to go ahead and make this fix in the master branch? 

Also as a heads up all the example .cfg files in data/ for point initialization that use start and stop times need to be updated, not sure when this changed, but end_year, end_month etc switched to stop_year, stop_month, etc but the cfg files use the old way.

**Comment by nwagenbrenner** [comment] 2020-10-07 13:59
@tfinney9 Your proposed fix looks good to me. If you commit it to the master branch I'll do some additional testing. I'll fix the .cfg example files too. I think the change from end_year to stop_year, etc. was part of a broader change we made for the new semi-lagrangian work.

**Comment by tfinney9** [comment] 2020-10-07 14:35
Sounds good! I have committed the change to the master branch. Thanks!

**Closed** 2021-05-25 17:54 UTC
