### ISSUE TITLE
Shadow effect in output winds

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#398] opened 2021-04-01 03:31 UTC
Hi
It has become apparent to us that though outside the safe zone, wind field shows shadow of coastlines almost symmetric along the central latitude of the domain. I use %20 larger DEM so I seem to be safely distant from  this behavior but I am not 100% certain on that. To my observations, this shadow behavior happens when we have land-sea contrast in input DEM. I replace all nodata vals with 0 before running WindNinja so water points are defined in DEM initialization.  With this arrangement  it is expected to have some activity over the water (with specified vegetation type) but mimicking coastline  as you see in the picture below is bothersome although it is apparent only in low speeds (less than 1-2m/s). This particular image  is the result of domain avg initialization with 5m/s wind at 0deg. Vegetation is set to trees.  Domain is [-123.2,37.8, -121.8,39.2]. The complete cfg file is like this:

num_threads=1
elevation_file=dem.tif
initialization_method=domainAverageInitialization
input_speed=5
input_direction=0
input_speed_units=mps
time_zone=GMT
input_wind_height=10
units_input_wind_height=m
number_time_steps=1
output_wind_height=20.0
output_speed_units=mph
units_output_wind_height=ft
output_path=./W123N038
mesh_resolution=250.0
units_mesh_resolution=m
vegetation=trees
write_goog_output=true
goog_out_resolution=500
units_goog_out_resolution=m
write_shapefile_output=false
write_ascii_output=true
write_farsite_atm=true

I don't recall reading about this kind of behavior anywhere in the documentations or in the issues threads here. Is this something known before or am I missing something in the initialization? 
regards   

![Capture](https://user-images.githubusercontent.com/53827558/113235327-d277ef80-9270-11eb-9168-d83e94610a48.png)

**Comment by nwagenbrenner** [comment] 2021-04-01 03:40
I'm not sure I understand exactly what the issues is. Can you provide your dem.tif and I'll take a look using your cfg inputs to reproduce the simulation?

**Comment by ncubukcu** [comment] 2021-04-01 03:42
US_DEM2016Modified.tif
<https://drive.google.com/file/d/1nneKzA5yzJehMoV31zQrC7dt1RXo9CLb/view?usp=drive_web>

**Comment by ncubukcu** [comment] 2021-04-01 04:01
Hi Natalie
I sent my elevation input above. As I indicated with red arrows above, wind field shows coastline out in the ocean. It is hard to notice this over the land but if you look carefully, you will see San Fransico Bay also showing up in the north side of the domain close to Clearlake area. I attached another image where I circled this behavior.
thanks

![Capture1](https://user-images.githubusercontent.com/53827558/113241646-1c66d280-927d-11eb-8ae9-8dd41b406e55.PNG)

**Comment by nwagenbrenner** [comment] 2021-04-01 16:15
I ran your simulation and looked at the Google Earth and raster output (shown below) and don't see this issue you are pointing out. Is it possible there is an error in a post-processing step? Can you take a look at the raw kmz and raster output and see if they look okay to you?


![Screenshot from 2021-04-01 10-13-20](https://user-images.githubusercontent.com/3696653/113323253-fec45800-92d2-11eb-9454-7c29108cbc6f.png)

**Comment by ncubukcu** [comment] 2021-04-01 17:33
Hi Natalie
Apologies for the confusion. I noticed this strange behaviour  in my
experiments using lcp files as input. I tried to simplify it before
presenting it to you using simple elevation and vegetation type. I thought
I checked it carefully but  I was wrong.
After your reply I realized that I was looking at the wrong output. Yes you
are right so what I experience does not happen with elevation as tif and
vegetation set to one kind. If you however, repeat the experiment  with the
attached lcp file you should get what I see. The lcp file generation may be
wrong or the projection may be not right but so far I did not see
anything.  Any clue you can provide on this would be a big help.
Thanks
nc
 W123N038.lcp
<https://drive.google.com/file/d/1n_o8hgjFxuMBbq9dqxGJPJ6rjy64tgxP/view?usp=drive_web>
 W123N038.prj
<https://drive.google.com/file/d/1JH2BgQNG0tU7oanAQoE5WfTcwbPSr00y/view?usp=drive_web>

**Comment by nwagenbrenner** [comment] 2021-04-06 21:31
Thanks for supplying the LCPs. We're looking into this and will get back to you soon.

**Comment by ncubukcu** [comment] 2021-04-23 16:10
Hi Natalie
Were you able to  take a look at this issue?  I also see  that in the lcp files aspect for flat areas defined as zero which also means north facing slopes. I wonder if there is a salient difference in definitions like this  I  overlooked.
regards,

**Comment by nwagenbrenner** [comment] 2021-04-26 15:43
@ncubukcu sorry for the slow reply. I'm still looking into this and will try to get you an answer soon.

**Comment by nwagenbrenner** [comment] 2021-05-05 18:21
@ncubukcu Thanks for reporting this issue. It turns out there was an error in how we were populating our roughness grids from the LCP files. We've just added a fix in the master branch. This should fix your issue. I'm closing this issue now, but let us know if you see any other problem. Thanks again for reporting this!

**Closed by nwagenbrenner** 2021-05-05 18:21 UTC

**Comment by ncubukcu** [comment] 2021-05-05 18:53
thank you very much Natalie
I will update our install and report back if there is a problem.. 
regards

**Comment by ncubukcu** [comment] 2021-05-06 14:44
Looks very consistent with underlying features now. Thank you very much Natalie
![image](https://user-images.githubusercontent.com/53827558/117317954-ff16bc80-ae57-11eb-91c2-2e4599b0919f.png)
