### ISSUE TITLE
finish the pdf writer

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#75] opened 2015-09-20 17:07 UTC
There are just a few things left to finish up the pdf output option. For one, it looks like it requires GDAL >= 2.0.0. I think it has to do with how the OGR ds is created/handled, but I didn't look very closely. At any rate, it runs/works with GDAL 2.0.0, but not  GDAL 1.10.1. Note that GDAL has to be compiled --with-poppler.

Other things that need to happen:

- remove the required "pdf_dem_filename" input (this isn't needed)
- make sure the output file name is being set correctly
- check that the windninja and topofire logos are being added and that all the images are a reasonable size
- unlink gdalwmscache/ 
- add the caltopo server as an alternate base map option (topofire is in data/relief.xml)
- verify that the hillshade base map option works if the caltopo/topofire basemaps aren't available
- add the pdf output option in the GUI

**Comment by jforthofer** [comment] 2015-09-21 15:02
So does a poppler library have to be added to the WindNinja installer and cmake also?  Or is poppler somehow compiled into the GDAL library?

**Comment by nwagenbrenner** [comment] 2015-09-21 16:06
Yes, GDAL has to be compiled with poppler, so it will have to be included in the installer. Installing poppler is simple on Linux, but looks like it could be messy to build it in Windows (I haven't tried). I don't think anything has to change in cmake unless we want to check for poppler support and disable the pdf writer if it's not available (that would probably be smart). I guess this is Kyle's specialty, maybe he has some comments.

**Comment by jforthofer** [comment] 2015-09-21 16:34
OK, yeah, this is Kyle's area.  But there will be some changes in cmake since that's where the code to tell the installer what to do is located (like copy the poppler dll into the correct location).

**Comment by nwagenbrenner** [comment] 2015-09-21 16:43
We don't link to poppler directly (only GDAL does), so I don't think there will be cmake changes (except what I mentioned before about checking whether GDAL is built with it), but I could be wrong.

**Comment by jforthofer** [comment] 2015-09-21 17:01
The installer on Windows will still need to know to copy the poppler dll to the WindNinja installation directory (just like it copies the GDAL dll, etc.).  The code for telling the installer to do what it does is located in cmake.

**Comment by nwagenbrenner** [comment] 2015-09-21 17:08
Yeah, you're right. I see this stuff now, starting around line 581 in the top level CMakeLists.txt file.

**Comment by ksshannon** [comment] 2015-09-21 20:32
There are now 3 pdf drivers, poppler, podofo, and pdfium.  pdfium is only a couple weeks old, and requires a patched version, podofo has the most liberal license and poppler is the most mature.  I will check and see if the output writer works with podofo, and act accordingly.  I can add cmake support as well.  Is the pdf output stuff in master?

**Comment by nwagenbrenner** [comment] 2015-09-21 20:40
Yes, it's in master.

**Comment by ksshannon** [comment] 2015-09-23 03:22
So pdf_dem_filename isn't used unless we can't get WMS, and use the hillshade from the DEM?  So it's always elevation_file, and that is only if we can't get anything else?

**Comment by ksshannon** [comment] 2015-09-23 03:23
I'll finish this up.

**Comment by nwagenbrenner** [comment] 2015-09-23 03:29
Yeah, pdf_dem_filename shouldn't be needed. If we can't get the basemap from topofire or caltopo, we should just use a hillshade from elevation_file like you said.

**Comment by ksshannon** [comment] 2015-10-08 14:56
Tamas' builds have all the dependencies we need, for all current (stable) MSVC versions (2010-2013):

gisinternals.com/sdk

just for documentation.

**Comment by ksshannon** [comment] 2016-02-02 16:17
Other things that need to happen:

> - remove the required "pdf_dem_filename" input (this isn't needed)
> - make sure the output file name is being set correctly
> - check that the windninja and topofire logos are being added and that all the images are a reasonable size
> - unlink gdalwmscache/
> - add the caltopo server as an alternate base map option (topofire is in data/relief.xml)
> - verify that the hillshade base map option works if the caltopo/topofire basemaps aren't available
>  add the pdf output option in the GUI

Comments:

- pdf_dem_filename is gone, a tempfile is used and destroyed for a ninjaArmy.
- AFAIK, the output filename looks good, but I didn't work on it.
- Can someone add the topofire logo?  Also which windninja logo?
- I don't think we should unlink the WMS cache.  If people do more than one set of runs on the same DEM (GUI or something), we don't have to go to the network.  It's a size-controlled cache, thoughts?
- 'Hillshade' map (just a grayscale relief, not a proper hillshade) works.  I am missing the max, but that is just a scaling issue.
- Added to GUI, need to properly disable(#91)

**Comment by ksshannon** [comment] 2016-02-02 16:20
Punchlist:

- [ ] Adjust resolution of raster to be coarser via tiff or PDF DPI
- [ ] Decrease legend size
- [ ] PDF always written in GUI, regardless of turned on/off
- [ ] Add topofire and windninja logos
- [ ] Add CalTopo

**Comment by nwagenbrenner** [comment] 2016-02-02 16:34
I added the topofire logo to images/. We were using wn-splash.png.

**Comment by nwagenbrenner** [comment] 2016-02-02 16:39
Also, I agree about the WMS cache.

**Comment by ksshannon** [comment] 2016-02-03 04:44
Fixes:
- Topofire logo added in c5369ff0c605da9ff03b875aada22ad5713660f4
- GUI fixed in 2e93a44339da3652d1b3aa0b374f9840ad350924
- Set legend size slightly smaller in 723013cacbb876ebb5afe117924f3feacc96950d

Issues:
- Resolution won't work for the rasters, so I'll just resample the DEM when we create the hillshade, to be done.
- WindNinja logo:  is this necessary?  I think it might clutter the pdf, and just cover terrain.  We don't do this for any other output.  Thoughts?
- Deferring CalTopo to a seperate ticket.

**Comment by nwagenbrenner** [comment] 2016-02-03 14:31
Maybe the logos don't have to cover up the map. What about something like this?

[mackay_270_10_09-23-2011_1330_250m.pdf](https://github.com/firelab/windninja/files/115776/mackay_270_10_09-23-2011_1330_250m.pdf)

The pdf output is a little different than our other outputs because it is a pre-formatted product that someone might print out as a hard copy. We need to give credit to TopoFire/CalTopo, but if the WindNinja logo isn't on there too it might appear that it's solely a TopoFire/CalTopo product? We'll also need a CalTopo logo if we use their layers.

**Comment by ksshannon** [comment] 2016-02-03 16:01
Okay, that logic makes sense.  I'm indifferent about where the images go, although maybe there is value in keeping the legend in the same place as the kmz?  Maybe not.  Sounds like a Jason style question.  Caltopo image will be added when the service is added.

**Comment by jforthofer** [comment] 2016-02-03 23:10
Right now I'm indifferent on where the logo and legend go...

**Comment by ksshannon** [comment] 2016-03-04 02:01
I am looking into the strange error that spits out when the runs end related to the driver !set stuff.  I believe it's fixed in the finish-pdf branch.  But there was something strange in git.  If I run git blame in master, I get this:

```
kyle@kyle-lrs-workstation:~/src/windninja$ git blame -L 97,102 src/ninja/ninjaArmy.cpp
^dddd3b8 (Kyle Shannon         2014-06-25 16:44:02 +0000  97) ninjaArmy::~ninjaA
^dddd3b8 (Kyle Shannon         2014-06-25 16:44:02 +0000  98) {
948b0523 (john                 2015-07-23 16:11:46 -0500  99)     GDALDriverH hD
948b0523 (john                 2015-07-23 16:11:46 -0500 100)     GDALDeleteData
0d6de7d5 (Natalie Wagenbrenner 2014-07-16 02:06:59 +0000 101)     for(unsigned i
0d6de7d5 (Natalie Wagenbrenner 2014-07-16 02:06:59 +0000 102)     {
```

Is that Levi?

kss

**Comment by nwagenbrenner** [comment] 2016-03-04 02:57
I noticed this before too. It's also in OutputWriter.cpp. I think it has to be Levi, but I don't know what happened to his user name.

**Comment by ksshannon** [comment] 2016-03-15 00:26
Added option for background in cli and gui in 99604911d2d6476796c78e8451849338b320f775.  @jforthofer, we weren't having any issues with the resolution stuff, can you double check that?  If you can't reproduce, I will leave it.

**Comment by jforthofer** [comment] 2016-03-15 16:34
The pdfs look fine on my computer.  At some point we might look into allowing control of the basemap resolution, but that can be done later by @nwagenbrenner .

**Comment by jforthofer** [comment] 2016-03-15 16:44
OK, I spoke too soon.  The size of the legend and WindNinja/TopoFire icons have problems.  If you do a simulation on a very small DEM (like say around 1/8 the size of mackay.tif), the legend and icons appear really, really big.  Are they being set to an absolute size, when they should be relative to the whole domain size?

**Comment by ksshannon** [comment] 2016-03-15 17:09
Copy, I'll check it tonight.

**Comment by ksshannon** [comment] 2016-03-15 23:26
Small pixel wise, or geographically?

**Comment by jforthofer** [comment] 2016-03-16 01:18
A small DEM extent geographically.

**Comment by ksshannon** [comment] 2016-03-23 00:58
So the issue ends up being that everything is defined in pixels.  Our legend has to be a reasonable size to render fonts.  When we get a really big dem, it is okay.  The PDF viewer just zooms properly.  When we are *really* small, the legend and other stuff just takes over.  The DEM is still the 'main' thing in the view.  I've added a little code that just inflates the input DEM to MIN(xSize, ySize) == 480.  Any feed back?  For most normal domains, we do fine.  In order to enforce proper constraints, we'd need to know the minimum legend size?

**Comment by nwagenbrenner** [comment] 2016-03-23 02:25
What if we add the legend and logos to white space like this. Does that avoid this issue?

[mackay_270_10_09-23-2011_1330_250m.pdf](https://github.com/firelab/windninja/files/185302/mackay_270_10_09-23-2011_1330_250m.pdf)

**Comment by ksshannon** [comment] 2016-03-23 02:40
Not sure, but I don't think so.  Everything is still defined in pixels.  What extra options did you set?

**Comment by nwagenbrenner** [comment] 2016-03-23 04:08
Levi did it. Here's what he said via email about this:

One of the creation options is BOTTOM_MARGIN. That allows us to add margin of whatever size we want to the bottom of the rasters. I'll test out that and see if I can place the logos in that extra space. One more thing I can do is add web URLs to the logos. When a user clicks on the image it will open the corresponding Firelab or Topofire websites.

**Comment by ksshannon** [comment] 2016-03-23 04:11
I still think we need to blow up the raster.  I think we don't need to
worry about it on normal domains.  It just looks terrible on irregular ones.

On Tue, Mar 22, 2016 at 10:08 PM, Natalie Wagenbrenner <
notifications@github.com> wrote:

> Levi did it. Here's what he said via email about this:
>
> One of the creation options is BOTTOM_MARGIN. That allows us to add margin
> of whatever size we want to the bottom of the rasters. I'll test out that
> and see if I can place the logos in that extra space. One more thing I can
> do is add web URLs to the logos. When a user clicks on the image it will
> open the corresponding Firelab or Topofire websites.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/firelab/windninja/issues/75#issuecomment-200165096>
>



-- 
Kyle

**Comment by nwagenbrenner** [comment] 2016-03-26 04:11
The pdf output stuff needs to be updated in ninjafoam.cpp to match what happens in ninja.cpp. Right now ninjafoam has its own output preparing/writing functions. Stuff will need to be restructured in ninja (volume grids are deallocated here, VTK output behavior is different between the two, etc.) before ninjafoam can inherit the output writing functions.  Or maybe it's worth moving stuff around in ninja so we don't have to override those. I guess that would be ideal.

**Comment by ksshannon** [comment] 2016-04-08 01:16
I think I've got the sizing issue fixed.  Now the hillshade is properly displayed in the center of the PDF regardless of output size.  I didn't test various dpi settings yet.  I still need to move the legend and the windninja logo too.  I guess all I did was make the output the requested size.

**Comment by ksshannon** [comment] 2016-04-10 21:14
The windninja logo appears to be placed properly now (3207e53b76595c801b3023a5ba1e326f02708e1a).  I need to test some other DEM files though.

**Comment by ksshannon** [comment] 2016-04-10 22:10
Legend is written to the lower left corner.  We should discuss size, and placement before doing much more work @jforthofer

**Comment by ksshannon** [comment] 2016-04-10 22:23
I'd like to close this and start filing issues for specific tasks.  This ticket is a little unwieldy.  Objections?

**Comment by jforthofer** [comment] 2016-04-12 00:14
Natalie and I think the legend should go in the lower left corner or someplace near the logos.  Ideally, they would all be in the white space at the bottom and not covering up the map.

**Comment by ksshannon** [comment] 2016-04-12 00:18
Okay, should there be a minimum size for that bottom margin?  I think there will have to be.

**Comment by nwagenbrenner** [comment] 2016-04-12 14:46
I think there should be a minimum size, maybe 1.5" or 2"? Seems like that should look okay?

**Comment by jforthofer** [comment] 2016-04-12 14:57
Yeah, that sounds about right.

**Comment by ksshannon** [comment] 2016-04-13 00:28
@nwagenbrenner @jforthofer I have all the images placed on the output.  It's pretty crammed with the bottom margin at 1.5".  I am closing this meta-ticket, open  new tickets for specific issues.  Please either attach an input DEM to the ticket, or reference a specific DEM in data/.  Levi's icons were padded better, and I think some whitespace helps, but I don't want to do anything without input.  All Levi's stuff wasn't constrained by output page size.

All new tickets should target 3.0.0 milestone, unless we decide to push it to 3.1.0

**Closed by ksshannon** 2016-04-13 00:28 UTC
Labels: component:core, component:output, confirmed, enhancement, priority:high
