### ISSUE TITLE
high NDFD values

### ISSUE THREAD

**Issue by oeon** [firelab/windninja#8] opened 2015-01-07 00:44 UTC
When trying to run WindNinja 2.4.0 with NDFD downloaded data for hour values ranging from 120-168 (5-7 days out), the program cannot solve. I'm quite certain the issue is with this particular parameter, as I have tested varying locations and DEM resolutions.

**Comment by ksshannon** [comment] 2015-01-07 01:33
oeon,
Does the progress start reporting non-sensical values, or does the program just fail?  I can't reproduce with the current development version, but I can try tomorrow on the 2.4.0 tag.

**Comment by oeon** [comment] 2015-01-07 18:32
I am seeing some negative percentage values in the console.

Datasource: http://lib.calpoly.edu/gis/browse.jsp?by=th&th=5  
Direct URL: http://gis.calpoly.edu/gis/data/slo_county%2Fdem%2Fcounty_dem%2Fcounty_dem.zip  
Preprocessing:
```
gdal_translate -projwin 5697304.33481 2291923.02541 5716422.70462 2275411.70603 -of GTiff C:\wninja\slo_county-dem-county_dem-county_dem\county_dem\w001001.adf C:/wninja/spooner-cp-dem.tif

gdalwarp -t_srs EPSG:26910 -r lanczos -of GTiff C:/wninja/spooner-cp-dem.tif C:/wninja/spooner-cp-dem-utm.tif
```

The program runs with NDFD value of 6 hours but with 168 hours it hangs at 71% completion. My parameters; spooner-cp-dem-utm.tif, brush vegetation, fine mesh resolution, default .kmz output.

**Comment by jforthofer** [comment] 2015-01-07 22:15
Fixed in 161a1d8a7d8cd54d46f79396df4b2b7f4879ec71.  Will be released to the public soon most likely as 2.4.1.

**Comment by jforthofer** [comment] 2015-01-07 23:01
Oeon,

We are trying to build a version to release right now with the bug fix, it should be available soon at firelab.org if all goes smoothly.  I'd recommend signing up for our WindNinja email list so you'll get emails when new versions come out.  You can sign up from here:
http://www.firelab.org/project/windninja
On the right hand side of the web page under the "Wind Modeling News" heading.

**Comment by oeon** [comment] 2015-01-07 23:09
@jforthofer very good, thank you! And thank you for the great software project.

I'll leave it to you to close this issue as you see fit. Cheers

**Comment by jforthofer** [comment] 2015-01-07 23:17
OK, let us know if you find any other problems...  It's actually somewhat rare for us to find bugs like this in the main code these days since it gets used so much.

**Closed by jforthofer** 2015-01-07 23:17 UTC
Labels: component:core, priority:med, severity:med
